const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  setOpacity: (v) => ipcRenderer.invoke('set-opacity', v),
  getOpacity: () => ipcRenderer.invoke('get-opacity'),
  setStealth: (v) => ipcRenderer.invoke('set-stealth', v),
  getStealth: () => ipcRenderer.invoke('get-stealth'),
  hide: () => ipcRenderer.invoke('hide'),
  quit: () => ipcRenderer.invoke('quit'),
  getUrls: () => ipcRenderer.invoke('get-urls'),
  setUrls: (urls) => ipcRenderer.invoke('set-urls', urls),
  showUrlMenu: () => ipcRenderer.invoke('show-url-menu'),
  reloadWebview: () => ipcRenderer.invoke('reload-webview'),
  setWebviewVisible: (v) => ipcRenderer.invoke('set-webview-visible', v),
  getMode: () => ipcRenderer.invoke('get-mode'),
  setMode: (mode) => ipcRenderer.invoke('set-mode', mode),
  getTranscriptionConfig: () => ipcRenderer.invoke('get-transcription-config'),
  setTranscriptionConfig: (cfg) => ipcRenderer.invoke('set-transcription-config', cfg),
  transcribe: (wav) => ipcRenderer.invoke('transcribe', wav),
  pasteText: (text) => ipcRenderer.invoke('paste-text', text),
  pickFile: (kind) => ipcRenderer.invoke('pick-file', kind),
  getCaptureConfig: () => ipcRenderer.invoke('get-capture-config'),
  setCaptureConfig: (cfg) => ipcRenderer.invoke('set-capture-config', cfg),
  selectCaptureArea: () => ipcRenderer.invoke('select-capture-area'),
  startCaptureLoop: () => ipcRenderer.invoke('start-capture-loop'),
  stopCaptureLoop: () => ipcRenderer.invoke('stop-capture-loop'),
  isCapturing: () => ipcRenderer.invoke('is-capturing'),
  getHotkeys: () => ipcRenderer.invoke('get-hotkeys'),
  setHotkey: (action, combo) => ipcRenderer.invoke('set-hotkey', action, combo),
  resetHotkey: (action) => ipcRenderer.invoke('reset-hotkey', action),
  resetAllHotkeys: () => ipcRenderer.invoke('reset-all-hotkeys'),
  onOpacityChanged: (cb) => ipcRenderer.on('opacity-changed', (_e, v) => cb(v)),
  onStealthChanged: (cb) => ipcRenderer.on('stealth-changed', (_e, v) => cb(v)),
  onCaptureText: (cb) => ipcRenderer.on('capture-text', (_e, v) => cb(v)),
  onCaptureError: (cb) => ipcRenderer.on('capture-error', (_e, v) => cb(v)),
  onCaptureRectChanged: (cb) => ipcRenderer.on('capture-rect-changed', (_e, v) => cb(v)),
  onCaptureState: (cb) => ipcRenderer.on('capture-state', (_e, v) => cb(v)),
  onHotkeysChanged: (cb) => ipcRenderer.on('hotkeys-changed', (_e, v) => cb(v)),
  onToggleRecording: (cb) => ipcRenderer.on('toggle-recording', () => cb()),
  onTogglePtt: (cb) => ipcRenderer.on('toggle-ptt', () => cb()),
  onSelectorClosed: (cb) => ipcRenderer.on('selector-closed', () => cb()),
  getNetworkConfig: () => ipcRenderer.invoke('get-network-config'),
  setNetworkConfig: (cfg) => ipcRenderer.invoke('set-network-config', cfg),
  getNetworkStatus: () => ipcRenderer.invoke('get-network-status'),
  startNetwork: () => ipcRenderer.invoke('start-network'),
  stopNetwork: () => ipcRenderer.invoke('stop-network'),
  sendSignaling: (msg) => ipcRenderer.send('signaling-out', msg),
  onSignaling: (cb) => ipcRenderer.on('signaling-in', (_e, v) => cb(v)),
  onNetworkStatus: (cb) => ipcRenderer.on('network-status', (_e, v) => cb(v)),
  onNetworkError: (cb) => ipcRenderer.on('network-error', (_e, v) => cb(v)),
});
