const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  setOpacity: (v) => ipcRenderer.invoke('set-opacity', v),
  getOpacity: () => ipcRenderer.invoke('get-opacity'),
  setStealth: (v) => ipcRenderer.invoke('set-stealth', v),
  getStealth: () => ipcRenderer.invoke('get-stealth'),
  setClickThrough: (v) => ipcRenderer.invoke('set-click-through', v),
  getClickThrough: () => ipcRenderer.invoke('get-click-through'),
  onClickThroughChanged: (cb) => ipcRenderer.on('click-through-changed', (_e, v) => cb(v)),
  sendStickyText: (text) => ipcRenderer.invoke('sticky-send-text', text),
  sendStickyImage: (dataUrl) => ipcRenderer.invoke('sticky-send-image', dataUrl),
  onChatIncoming: (cb) => ipcRenderer.on('chat-incoming', (_e, v) => cb(v)),
  onChatClear: (cb) => ipcRenderer.on('chat-clear', () => cb()),
  hide: () => ipcRenderer.invoke('hide'),
  quit: () => ipcRenderer.invoke('quit'),
  getUrls: () => ipcRenderer.invoke('get-urls'),
  setUrls: (urls) => ipcRenderer.invoke('set-urls', urls),
  showUrlMenu: () => ipcRenderer.invoke('show-url-menu'),
  reloadWebview: () => ipcRenderer.invoke('reload-webview'),
  setWebviewVisible: (v) => ipcRenderer.invoke('set-webview-visible', v),
  navigateUrl: (url) => ipcRenderer.invoke('navigate-url', url),
  webviewBack: () => ipcRenderer.invoke('webview-back'),
  webviewForward: () => ipcRenderer.invoke('webview-forward'),
  getWebviewUrl: () => ipcRenderer.invoke('get-webview-url'),
  onWebviewUrlChanged: (cb) => ipcRenderer.on('webview-url-changed', (_e, v) => cb(v)),
  getMode: () => ipcRenderer.invoke('get-mode'),
  setMode: (mode) => ipcRenderer.invoke('set-mode', mode),
  getTranscriptionConfig: () => ipcRenderer.invoke('get-transcription-config'),
  setTranscriptionConfig: (cfg) => ipcRenderer.invoke('set-transcription-config', cfg),
  transcribe: (wav) => ipcRenderer.invoke('transcribe', wav),
  pasteText: (text) => ipcRenderer.invoke('paste-text', text),
  pickFile: (kind) => ipcRenderer.invoke('pick-file', kind),
  getCaptureConfig: () => ipcRenderer.invoke('get-capture-config'),
  setCaptureConfig: (cfg) => ipcRenderer.invoke('set-capture-config', cfg),
  selectCaptureArea: () => ipcRenderer.invoke('select-capture-area'),
  startCaptureLoop: () => ipcRenderer.invoke('start-capture-loop'),
  stopCaptureLoop: () => ipcRenderer.invoke('stop-capture-loop'),
  isCapturing: () => ipcRenderer.invoke('is-capturing'),
  getHotkeys: () => ipcRenderer.invoke('get-hotkeys'),
  setHotkey: (action, combo) => ipcRenderer.invoke('set-hotkey', action, combo),
  resetHotkey: (action) => ipcRenderer.invoke('reset-hotkey', action),
  resetAllHotkeys: () => ipcRenderer.invoke('reset-all-hotkeys'),
  onOpacityChanged: (cb) => ipcRenderer.on('opacity-changed', (_e, v) => cb(v)),
  onStealthChanged: (cb) => ipcRenderer.on('stealth-changed', (_e, v) => cb(v)),
  onCaptureText: (cb) => ipcRenderer.on('capture-text', (_e, v) => cb(v)),
  onCaptureError: (cb) => ipcRenderer.on('capture-error', (_e, v) => cb(v)),
  onCaptureRectChanged: (cb) => ipcRenderer.on('capture-rect-changed', (_e, v) => cb(v)),
  onCaptureState: (cb) => ipcRenderer.on('capture-state', (_e, v) => cb(v)),
  onHotkeysChanged: (cb) => ipcRenderer.on('hotkeys-changed', (_e, v) => cb(v)),
  onToggleRecording: (cb) => ipcRenderer.on('toggle-recording', () => cb()),
  onToggleMode: (cb) => ipcRenderer.on('toggle-mode', () => cb()),
  onTogglePtt: (cb) => ipcRenderer.on('toggle-ptt', () => cb()),
  onSelectorClosed: (cb) => ipcRenderer.on('selector-closed', () => cb()),
  getNetworkConfig: () => ipcRenderer.invoke('get-network-config'),
  setNetworkConfig: (cfg) => ipcRenderer.invoke('set-network-config', cfg),
  getNetworkStatus: () => ipcRenderer.invoke('get-network-status'),
  startNetwork: () => ipcRenderer.invoke('start-network'),
  stopNetwork: () => ipcRenderer.invoke('stop-network'),
  configureFirewall: () => ipcRenderer.invoke('configure-firewall'),
  kickSupporter: (id) => ipcRenderer.invoke('kick-supporter', id),
  logAppend: (line) => ipcRenderer.invoke('log-append', line),
  logRecent: () => ipcRenderer.invoke('log-recent'),
  logClear: () => ipcRenderer.invoke('log-clear'),
  logOpen: () => ipcRenderer.invoke('log-open'),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  installUpdateNow: () => ipcRenderer.invoke('install-update-now'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  onUpdaterStatus: (cb) => ipcRenderer.on('updater-status', (_e, v) => cb(v)),
  sendSignaling: (msg) => ipcRenderer.send('signaling-out', msg),
  onSignaling: (cb) => ipcRenderer.on('signaling-in', (_e, v) => cb(v)),
  onNetworkStatus: (cb) => ipcRenderer.on('network-status', (_e, v) => cb(v)),
  onNetworkError: (cb) => ipcRenderer.on('network-error', (_e, v) => cb(v)),
  openSticky: () => ipcRenderer.invoke('sticky-open'),
  closeSticky: () => ipcRenderer.invoke('sticky-close'),
  clearSticky: () => ipcRenderer.invoke('sticky-clear'),
  injectTestChat: (text) => ipcRenderer.invoke('inject-test-chat', text),
  sendChatText: (text) => ipcRenderer.invoke('chat-send-text', text),
  sendChatImage: (dataUrl) => ipcRenderer.invoke('chat-send-image', dataUrl),
  onKickedBySpeaker: (cb) => ipcRenderer.on('kicked-by-speaker', () => cb()),
  onHelpRequestReceived: (cb) => ipcRenderer.on('help-request-received', (_e, v) => cb(v)),
  getMicMode: () => ipcRenderer.invoke('get-mic-mode'),
  setMicMode: (mode) => ipcRenderer.invoke('set-mic-mode', mode),
  cycleMicMode: () => ipcRenderer.invoke('cycle-mic-mode'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  onMicModeChanged: (cb) => ipcRenderer.on('mic-mode-changed', (_e, v) => cb(v)),
  getWelcomeSeen: () => ipcRenderer.invoke('get-welcome-seen'),
  setWelcomeSeen: (v) => ipcRenderer.invoke('set-welcome-seen', v),
  injectToWebview: (text) => ipcRenderer.invoke('inject-to-webview', text),
  webviewEditTail: (deleteCount, insert) => ipcRenderer.invoke('webview-edit-tail', { deleteCount, insert }),
  exportCookies: () => ipcRenderer.invoke('cookies-export'),
  importCookies: () => ipcRenderer.invoke('cookies-import'),
  getPrompts: () => ipcRenderer.invoke('get-prompts'),
  savePrompt: (prompt) => ipcRenderer.invoke('save-prompt', prompt),
  deletePrompt: (id) => ipcRenderer.invoke('delete-prompt', id),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  showPromptMenu: () => ipcRenderer.invoke('show-prompt-menu'),
  exportPrompts: () => ipcRenderer.invoke('prompts-export'),
  importPrompts: () => ipcRenderer.invoke('prompts-import'),
  startDeepgramStream: (cfg) => ipcRenderer.invoke('start-deepgram-stream', cfg),
  stopDeepgramStream: () => ipcRenderer.invoke('stop-deepgram-stream'),
  sendAudioChunk: (buf) => ipcRenderer.send('audio-chunk', buf),
  saveSessionLog: () => ipcRenderer.invoke('save-session-log'),
  clearSessionLog: () => ipcRenderer.invoke('clear-session-log'),
  sessionLogAdd: (entry) => ipcRenderer.send('session-log-add', entry),
  onTranscriptLive: (cb) => ipcRenderer.on('transcript-live', (_e, v) => cb(v)),
  onTranscriptLiveError: (cb) => ipcRenderer.on('transcript-live-error', (_e, v) => cb(v)),
  onUtteranceEnd: (cb) => ipcRenderer.on('transcript-utterance-end', () => cb()),
  getDesktopSourceId: () => ipcRenderer.invoke('get-desktop-source-id'),
});
