const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  setOpacity: (v) => ipcRenderer.invoke('set-opacity', v),
  getOpacity: () => ipcRenderer.invoke('get-opacity'),
  setStealth: (v) => ipcRenderer.invoke('set-stealth', v),
  getStealth: () => ipcRenderer.invoke('get-stealth'),
  setClickThrough: (v) => ipcRenderer.invoke('set-click-through', v),
  getClickThrough: () => ipcRenderer.invoke('get-click-through'),
  onClickThroughChanged: (cb) => ipcRenderer.on('click-through-changed', (_e, v) => cb(v)),
  sendStickyText: (text) => ipcRenderer.invoke('sticky-send-text', text),
  sendStickyImage: (dataUrl) => ipcRenderer.invoke('sticky-send-image', dataUrl),
  sendStickyRich: (markdown) => ipcRenderer.invoke('sticky-send-rich', markdown),
  onChatIncoming: (cb) => ipcRenderer.on('chat-incoming', (_e, v) => cb(v)),
  onChatClear: (cb) => ipcRenderer.on('chat-clear', () => cb()),
  hide: () => ipcRenderer.invoke('hide'),
  quit: () => ipcRenderer.invoke('quit'),
  onScrollAnswer: (cb) => ipcRenderer.on('scroll-answer', (_e, v) => cb(v)),
  getMode: () => ipcRenderer.invoke('get-mode'),
  setMode: (mode) => ipcRenderer.invoke('set-mode', mode),
  getTranscriptionConfig: () => ipcRenderer.invoke('get-transcription-config'),
  setTranscriptionConfig: (cfg) => ipcRenderer.invoke('set-transcription-config', cfg),
  getMeetingConfig: () => ipcRenderer.invoke('get-meeting-config'),
  setMeetingConfig: (cfg) => ipcRenderer.invoke('set-meeting-config', cfg),
  transcribe: (wav) => ipcRenderer.invoke('transcribe', wav),
  pasteText: (text) => ipcRenderer.invoke('paste-text', text),
  getCaptureConfig: () => ipcRenderer.invoke('get-capture-config'),
  setCaptureConfig: (cfg) => ipcRenderer.invoke('set-capture-config', cfg),
  selectCaptureArea: () => ipcRenderer.invoke('select-capture-area'),
  startCaptureLoop: () => ipcRenderer.invoke('start-capture-loop'),
  stopCaptureLoop: () => ipcRenderer.invoke('stop-capture-loop'),
  isCapturing: () => ipcRenderer.invoke('is-capturing'),
  getHotkeys: () => ipcRenderer.invoke('get-hotkeys'),
  setHotkey: (action, combo) => ipcRenderer.invoke('set-hotkey', action, combo),
  resetHotkey: (action) => ipcRenderer.invoke('reset-hotkey', action),
  resetAllHotkeys: () => ipcRenderer.invoke('reset-all-hotkeys'),
  onOpacityChanged: (cb) => ipcRenderer.on('opacity-changed', (_e, v) => cb(v)),
  onStealthChanged: (cb) => ipcRenderer.on('stealth-changed', (_e, v) => cb(v)),
  onCaptureText: (cb) => ipcRenderer.on('capture-text', (_e, v) => cb(v)),
  onCaptureError: (cb) => ipcRenderer.on('capture-error', (_e, v) => cb(v)),
  onCaptureRectChanged: (cb) => ipcRenderer.on('capture-rect-changed', (_e, v) => cb(v)),
  onCaptureState: (cb) => ipcRenderer.on('capture-state', (_e, v) => cb(v)),
  onHotkeysChanged: (cb) => ipcRenderer.on('hotkeys-changed', (_e, v) => cb(v)),
  onToggleRecording: (cb) => ipcRenderer.on('toggle-recording', () => cb()),
  onToggleMode: (cb) => ipcRenderer.on('toggle-mode', () => cb()),
  onClearMeetBubble: (cb) => ipcRenderer.on('clear-meet-bubble', () => cb()),
  onTogglePtt: (cb) => ipcRenderer.on('toggle-ptt', () => cb()),
  onSelectorClosed: (cb) => ipcRenderer.on('selector-closed', () => cb()),
  getNetworkConfig: () => ipcRenderer.invoke('get-network-config'),
  setNetworkConfig: (cfg) => ipcRenderer.invoke('set-network-config', cfg),
  getNetworkStatus: () => ipcRenderer.invoke('get-network-status'),
  startNetwork: () => ipcRenderer.invoke('start-network'),
  stopNetwork: () => ipcRenderer.invoke('stop-network'),
  configureFirewall: () => ipcRenderer.invoke('configure-firewall'),
  kickSupporter: (id) => ipcRenderer.invoke('kick-supporter', id),
  logAppend: (line) => ipcRenderer.invoke('log-append', line),
  logRecent: () => ipcRenderer.invoke('log-recent'),
  logClear: () => ipcRenderer.invoke('log-clear'),
  logOpen: () => ipcRenderer.invoke('log-open'),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  installUpdateNow: () => ipcRenderer.invoke('install-update-now'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  onUpdaterStatus: (cb) => ipcRenderer.on('updater-status', (_e, v) => cb(v)),
  sendSignaling: (msg) => ipcRenderer.send('signaling-out', msg),
  onSignaling: (cb) => ipcRenderer.on('signaling-in', (_e, v) => cb(v)),
  onNetworkStatus: (cb) => ipcRenderer.on('network-status', (_e, v) => cb(v)),
  onNetworkError: (cb) => ipcRenderer.on('network-error', (_e, v) => cb(v)),
  openSticky: () => ipcRenderer.invoke('sticky-open'),
  closeSticky: () => ipcRenderer.invoke('sticky-close'),
  clearSticky: () => ipcRenderer.invoke('sticky-clear'),
  injectTestChat: (text) => ipcRenderer.invoke('inject-test-chat', text),
  sendChatText: (text) => ipcRenderer.invoke('chat-send-text', text),
  sendChatImage: (dataUrl) => ipcRenderer.invoke('chat-send-image', dataUrl),
  onKickedBySpeaker: (cb) => ipcRenderer.on('kicked-by-speaker', () => cb()),
  onHelpRequestReceived: (cb) => ipcRenderer.on('help-request-received', (_e, v) => cb(v)),
  getMicMode: () => ipcRenderer.invoke('get-mic-mode'),
  setMicMode: (mode) => ipcRenderer.invoke('set-mic-mode', mode),
  cycleMicMode: () => ipcRenderer.invoke('cycle-mic-mode'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  onMicModeChanged: (cb) => ipcRenderer.on('mic-mode-changed', (_e, v) => cb(v)),
  getWelcomeSeen: () => ipcRenderer.invoke('get-welcome-seen'),
  setWelcomeSeen: (v) => ipcRenderer.invoke('set-welcome-seen', v),
  generateAnswer: (question, images, forcedMode, extra) => ipcRenderer.invoke('generate-answer', { question, images, forcedMode, ...(extra || {}) }),
  stopAnswer: () => ipcRenderer.invoke('stop-answer'),
  clearAnswerMemory: () => ipcRenderer.invoke('clear-answer-memory'),
  sessionList: () => ipcRenderer.invoke('session-list'),
  sessionMeta: (id) => ipcRenderer.invoke('session-meta', id),
  sessionNew: (meta) => ipcRenderer.invoke('session-new', meta),
  sessionLoad: (id) => ipcRenderer.invoke('session-load', id),
  sessionRecordMeet: (payload) => ipcRenderer.invoke('session-record-meet', payload),
  sessionDelete: (id) => ipcRenderer.invoke('session-delete', id),
  sessionUpdateProfile: (id, profile) => ipcRenderer.invoke('session-update-profile', { id, profile }),
  getDefaultProfile: () => ipcRenderer.invoke('get-default-profile'),
  profilesList: () => ipcRenderer.invoke('profiles-list'),
  profileSaveNew: (label, profile) => ipcRenderer.invoke('profile-save-new', { label, profile }),
  profileUpdate: (id, label, profile) => ipcRenderer.invoke('profile-update', { id, label, profile }),
  profileDelete: (id) => ipcRenderer.invoke('profile-delete', id),
  profileSetActive: (id) => ipcRenderer.invoke('profile-set-active', id),
  kbClear: () => ipcRenderer.invoke('kb-clear'),
  sessionKbGet: (id) => ipcRenderer.invoke('session-kb-get', id),
  sessionKbAdd: (id, kind, name, data) => ipcRenderer.invoke('session-kb-add', { id, kind, name, data }),
  sessionKbRemove: (id, kind, index) => ipcRenderer.invoke('session-kb-remove', { id, kind, index }),
  infoOpen: (profile) => ipcRenderer.invoke('info-open', profile),
  infoClose: () => ipcRenderer.invoke('info-close'),
  getAnswerConfig: () => ipcRenderer.invoke('get-answer-config'),
  listXaiModels: () => ipcRenderer.invoke('list-answer-models'),
  listAnswerModels: () => ipcRenderer.invoke('list-answer-models'),
  kbAdd: (kind, name, data) => ipcRenderer.invoke('kb-add', { kind, name, data }),
  kbRemove: (kind, index) => ipcRenderer.invoke('kb-remove', { kind, index }),
  kbGet: () => ipcRenderer.invoke('kb-get'),
  setAnswerConfig: (cfg) => ipcRenderer.invoke('set-answer-config', cfg),
  onAnswerStart: (cb) => ipcRenderer.on('answer-start', (_e, v) => cb(v)),
  onAnswerChunk: (cb) => ipcRenderer.on('answer-chunk', (_e, v) => cb(v)),
  onAnswerDone: (cb) => ipcRenderer.on('answer-done', (_e, v) => cb(v)),
  onAnswerError: (cb) => ipcRenderer.on('answer-error', (_e, v) => cb(v)),
  onTriggerGetAnswer: (cb) => ipcRenderer.on('trigger-get-answer', () => cb()),
  onTriggerScreenshot: (cb) => ipcRenderer.on('trigger-screenshot', () => cb()),
  onSnipImage: (cb) => ipcRenderer.on('snip-image', (_e, v) => cb(v)),
  getAvoidPhrases: () => ipcRenderer.invoke('get-avoid-phrases'),
  setAvoidPhrases: (text) => ipcRenderer.invoke('set-avoid-phrases', text),
  writeToIde: (code, speedFactor) => ipcRenderer.invoke('write-to-ide', { code, speedFactor }),
  stopIdeTyping:   () => ipcRenderer.invoke('stop-ide-typing'),
  onIdeTypingState: (cb) => ipcRenderer.on('ide-typing-state', (_e, s) => cb(s)),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  showModelMenu: (anchor) => ipcRenderer.invoke('show-model-menu', anchor),
  onModelSelected: (cb) => ipcRenderer.on('model-selected', (_e, id) => cb(id)),
  onAnswerConfigChanged: (cb) => ipcRenderer.on('answer-config-changed', (_e, cfg) => cb(cfg)),
  startDeepgramStream: (cfg) => ipcRenderer.invoke('start-deepgram-stream', cfg),
  stopDeepgramStream: () => ipcRenderer.invoke('stop-deepgram-stream'),
  startXaiStream: (cfg) => ipcRenderer.invoke('start-xai-stream', cfg),
  stopXaiStream: () => ipcRenderer.invoke('stop-xai-stream'),
  sendAudioChunk: (buf) => ipcRenderer.send('audio-chunk', buf),
  saveSessionLog: (name) => ipcRenderer.invoke('save-session-log', name),
  sessionFinalize: (company, position) => ipcRenderer.invoke('session-finalize', { company, position }),
  clearSessionLog: () => ipcRenderer.invoke('clear-session-log'),
  sessionLogAdd: (entry) => ipcRenderer.send('session-log-add', entry),
  onTranscriptLive: (cb) => ipcRenderer.on('transcript-live', (_e, v) => cb(v)),
  onTranscriptLiveError: (cb) => ipcRenderer.on('transcript-live-error', (_e, v) => cb(v)),
  onUtteranceEnd: (cb) => ipcRenderer.on('transcript-utterance-end', () => cb()),
  getDesktopSourceId: () => ipcRenderer.invoke('get-desktop-source-id'),
  getCursorScreenSourceId: () => ipcRenderer.invoke('get-cursor-screen-source-id'),
  getCursorDisplayIndex: () => ipcRenderer.invoke('get-cursor-display-index'),
  getAllScreenSourceIds: () => ipcRenderer.invoke('get-all-screen-source-ids'),
  // Latency optimizations
  warmApiConnection: () => ipcRenderer.invoke('warm-api-connection'),
  speculativeStart: (opts) => ipcRenderer.invoke('speculative-start', opts),  // opts includes forcedMode
  speculativeCommit: (opts) => ipcRenderer.invoke('speculative-commit', opts),
  speculativeCancel: () => ipcRenderer.invoke('speculative-cancel'),
  onAnswerCancelSpeculative: (cb) => ipcRenderer.on('answer-cancel-speculative', () => cb()),
  onAnswerCommitSpeculative: (cb) => ipcRenderer.on('answer-commit-speculative', () => cb()),
});
