// Generated by scripts/license-keygen.js — license signing key. Do not distribute.
module.exports = "-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEICcoF/Bl26VfJoICFL1x5Yhnp56OfglbyBbReAX4Typu\n-----END PRIVATE KEY-----\n";
