// Country → cities → IANA timezone, for the profile step. Picking a city
// fills the timezone automatically; a city not in the list can still be typed.
// Kept deliberately compact: major cities per country, remote-hiring markets first.
window.GEO = [
  { c: 'United States', cities: [
    ['New York', 'America/New_York'], ['Boston', 'America/New_York'], ['Washington, DC', 'America/New_York'], ['Miami', 'America/New_York'], ['Atlanta', 'America/New_York'],
    ['Chicago', 'America/Chicago'], ['Austin', 'America/Chicago'], ['Dallas', 'America/Chicago'], ['Houston', 'America/Chicago'], ['Minneapolis', 'America/Chicago'],
    ['Denver', 'America/Denver'], ['Phoenix', 'America/Phoenix'], ['Salt Lake City', 'America/Denver'],
    ['San Francisco', 'America/Los_Angeles'], ['Los Angeles', 'America/Los_Angeles'], ['Seattle', 'America/Los_Angeles'], ['San Diego', 'America/Los_Angeles'], ['Portland', 'America/Los_Angeles'], ['Las Vegas', 'America/Los_Angeles'],
  ] },
  { c: 'Canada', cities: [['Toronto', 'America/Toronto'], ['Montreal', 'America/Toronto'], ['Ottawa', 'America/Toronto'], ['Vancouver', 'America/Vancouver'], ['Calgary', 'America/Edmonton'], ['Edmonton', 'America/Edmonton'], ['Winnipeg', 'America/Winnipeg'], ['Halifax', 'America/Halifax']] },
  { c: 'Mexico', cities: [['Mexico City', 'America/Mexico_City'], ['Guadalajara', 'America/Mexico_City'], ['Monterrey', 'America/Monterrey'], ['Tijuana', 'America/Tijuana'], ['Cancún', 'America/Cancun']] },
  { c: 'Brazil', cities: [['São Paulo', 'America/Sao_Paulo'], ['Rio de Janeiro', 'America/Sao_Paulo'], ['Belo Horizonte', 'America/Sao_Paulo'], ['Curitiba', 'America/Sao_Paulo'], ['Porto Alegre', 'America/Sao_Paulo'], ['Brasília', 'America/Sao_Paulo'], ['Recife', 'America/Recife'], ['Manaus', 'America/Manaus']] },
  { c: 'Argentina', cities: [['Buenos Aires', 'America/Argentina/Buenos_Aires'], ['Córdoba', 'America/Argentina/Cordoba'], ['Rosario', 'America/Argentina/Buenos_Aires'], ['Mendoza', 'America/Argentina/Mendoza']] },
  { c: 'Colombia', cities: [['Bogotá', 'America/Bogota'], ['Medellín', 'America/Bogota'], ['Cali', 'America/Bogota']] },
  { c: 'Chile', cities: [['Santiago', 'America/Santiago'], ['Valparaíso', 'America/Santiago']] },
  { c: 'United Kingdom', cities: [['London', 'Europe/London'], ['Manchester', 'Europe/London'], ['Birmingham', 'Europe/London'], ['Leeds', 'Europe/London'], ['Bristol', 'Europe/London'], ['Edinburgh', 'Europe/London'], ['Glasgow', 'Europe/London'], ['Cambridge', 'Europe/London'], ['Belfast', 'Europe/London']] },
  { c: 'Ireland', cities: [['Dublin', 'Europe/Dublin'], ['Cork', 'Europe/Dublin'], ['Galway', 'Europe/Dublin']] },
  { c: 'Germany', cities: [['Berlin', 'Europe/Berlin'], ['Munich', 'Europe/Berlin'], ['Hamburg', 'Europe/Berlin'], ['Frankfurt', 'Europe/Berlin'], ['Cologne', 'Europe/Berlin'], ['Stuttgart', 'Europe/Berlin'], ['Düsseldorf', 'Europe/Berlin'], ['Leipzig', 'Europe/Berlin']] },
  { c: 'France', cities: [['Paris', 'Europe/Paris'], ['Lyon', 'Europe/Paris'], ['Marseille', 'Europe/Paris'], ['Toulouse', 'Europe/Paris'], ['Bordeaux', 'Europe/Paris'], ['Nantes', 'Europe/Paris'], ['Lille', 'Europe/Paris']] },
  { c: 'Spain', cities: [['Madrid', 'Europe/Madrid'], ['Barcelona', 'Europe/Madrid'], ['Valencia', 'Europe/Madrid'], ['Seville', 'Europe/Madrid'], ['Málaga', 'Europe/Madrid'], ['Bilbao', 'Europe/Madrid']] },
  { c: 'Portugal', cities: [['Lisbon', 'Europe/Lisbon'], ['Porto', 'Europe/Lisbon'], ['Braga', 'Europe/Lisbon'], ['Coimbra', 'Europe/Lisbon']] },
  { c: 'Italy', cities: [['Milan', 'Europe/Rome'], ['Rome', 'Europe/Rome'], ['Turin', 'Europe/Rome'], ['Bologna', 'Europe/Rome'], ['Florence', 'Europe/Rome'], ['Naples', 'Europe/Rome']] },
  { c: 'Netherlands', cities: [['Amsterdam', 'Europe/Amsterdam'], ['Rotterdam', 'Europe/Amsterdam'], ['The Hague', 'Europe/Amsterdam'], ['Utrecht', 'Europe/Amsterdam'], ['Eindhoven', 'Europe/Amsterdam']] },
  { c: 'Belgium', cities: [['Brussels', 'Europe/Brussels'], ['Antwerp', 'Europe/Brussels'], ['Ghent', 'Europe/Brussels'], ['Leuven', 'Europe/Brussels']] },
  { c: 'Switzerland', cities: [['Zurich', 'Europe/Zurich'], ['Geneva', 'Europe/Zurich'], ['Basel', 'Europe/Zurich'], ['Bern', 'Europe/Zurich'], ['Lausanne', 'Europe/Zurich']] },
  { c: 'Austria', cities: [['Vienna', 'Europe/Vienna'], ['Graz', 'Europe/Vienna'], ['Linz', 'Europe/Vienna'], ['Salzburg', 'Europe/Vienna']] },
  { c: 'Poland', cities: [['Warsaw', 'Europe/Warsaw'], ['Kraków', 'Europe/Warsaw'], ['Wrocław', 'Europe/Warsaw'], ['Gdańsk', 'Europe/Warsaw'], ['Poznań', 'Europe/Warsaw'], ['Łódź', 'Europe/Warsaw'], ['Katowice', 'Europe/Warsaw'], ['Lublin', 'Europe/Warsaw'], ['Szczecin', 'Europe/Warsaw']] },
  { c: 'Romania', cities: [['Bucharest', 'Europe/Bucharest'], ['Cluj-Napoca', 'Europe/Bucharest'], ['Timișoara', 'Europe/Bucharest'], ['Iași', 'Europe/Bucharest'], ['Brașov', 'Europe/Bucharest'], ['Constanța', 'Europe/Bucharest'], ['Sibiu', 'Europe/Bucharest'], ['Oradea', 'Europe/Bucharest']] },
  { c: 'Moldova', cities: [['Chișinău', 'Europe/Chisinau']] },
  { c: 'Czechia', cities: [['Prague', 'Europe/Prague'], ['Brno', 'Europe/Prague'], ['Ostrava', 'Europe/Prague']] },
  { c: 'Slovakia', cities: [['Bratislava', 'Europe/Bratislava'], ['Košice', 'Europe/Bratislava']] },
  { c: 'Hungary', cities: [['Budapest', 'Europe/Budapest'], ['Debrecen', 'Europe/Budapest'], ['Szeged', 'Europe/Budapest']] },
  { c: 'Ukraine', cities: [['Kyiv', 'Europe/Kyiv'], ['Lviv', 'Europe/Kyiv'], ['Kharkiv', 'Europe/Kyiv'], ['Odesa', 'Europe/Kyiv'], ['Dnipro', 'Europe/Kyiv']] },
  { c: 'Bulgaria', cities: [['Sofia', 'Europe/Sofia'], ['Plovdiv', 'Europe/Sofia'], ['Varna', 'Europe/Sofia']] },
  { c: 'Serbia', cities: [['Belgrade', 'Europe/Belgrade'], ['Novi Sad', 'Europe/Belgrade'], ['Niš', 'Europe/Belgrade']] },
  { c: 'Croatia', cities: [['Zagreb', 'Europe/Zagreb'], ['Split', 'Europe/Zagreb'], ['Rijeka', 'Europe/Zagreb']] },
  { c: 'Greece', cities: [['Athens', 'Europe/Athens'], ['Thessaloniki', 'Europe/Athens']] },
  { c: 'Turkey', cities: [['Istanbul', 'Europe/Istanbul'], ['Ankara', 'Europe/Istanbul'], ['Izmir', 'Europe/Istanbul']] },
  { c: 'Sweden', cities: [['Stockholm', 'Europe/Stockholm'], ['Gothenburg', 'Europe/Stockholm'], ['Malmö', 'Europe/Stockholm']] },
  { c: 'Norway', cities: [['Oslo', 'Europe/Oslo'], ['Bergen', 'Europe/Oslo'], ['Trondheim', 'Europe/Oslo']] },
  { c: 'Denmark', cities: [['Copenhagen', 'Europe/Copenhagen'], ['Aarhus', 'Europe/Copenhagen'], ['Odense', 'Europe/Copenhagen']] },
  { c: 'Finland', cities: [['Helsinki', 'Europe/Helsinki'], ['Tampere', 'Europe/Helsinki'], ['Turku', 'Europe/Helsinki']] },
  { c: 'Estonia', cities: [['Tallinn', 'Europe/Tallinn'], ['Tartu', 'Europe/Tallinn']] },
  { c: 'Latvia', cities: [['Riga', 'Europe/Riga']] },
  { c: 'Lithuania', cities: [['Vilnius', 'Europe/Vilnius'], ['Kaunas', 'Europe/Vilnius']] },
  { c: 'Georgia', cities: [['Tbilisi', 'Asia/Tbilisi'], ['Batumi', 'Asia/Tbilisi']] },
  { c: 'Armenia', cities: [['Yerevan', 'Asia/Yerevan']] },
  { c: 'Israel', cities: [['Tel Aviv', 'Asia/Jerusalem'], ['Jerusalem', 'Asia/Jerusalem'], ['Haifa', 'Asia/Jerusalem']] },
  { c: 'United Arab Emirates', cities: [['Dubai', 'Asia/Dubai'], ['Abu Dhabi', 'Asia/Dubai'], ['Sharjah', 'Asia/Dubai']] },
  { c: 'Saudi Arabia', cities: [['Riyadh', 'Asia/Riyadh'], ['Jeddah', 'Asia/Riyadh']] },
  { c: 'Egypt', cities: [['Cairo', 'Africa/Cairo'], ['Alexandria', 'Africa/Cairo']] },
  { c: 'South Africa', cities: [['Cape Town', 'Africa/Johannesburg'], ['Johannesburg', 'Africa/Johannesburg'], ['Durban', 'Africa/Johannesburg'], ['Pretoria', 'Africa/Johannesburg']] },
  { c: 'Nigeria', cities: [['Lagos', 'Africa/Lagos'], ['Abuja', 'Africa/Lagos']] },
  { c: 'Kenya', cities: [['Nairobi', 'Africa/Nairobi'], ['Mombasa', 'Africa/Nairobi']] },
  { c: 'India', cities: [['Bengaluru', 'Asia/Kolkata'], ['Hyderabad', 'Asia/Kolkata'], ['Pune', 'Asia/Kolkata'], ['Mumbai', 'Asia/Kolkata'], ['Chennai', 'Asia/Kolkata'], ['Delhi', 'Asia/Kolkata'], ['Gurugram', 'Asia/Kolkata'], ['Noida', 'Asia/Kolkata'], ['Kolkata', 'Asia/Kolkata'], ['Ahmedabad', 'Asia/Kolkata']] },
  { c: 'Pakistan', cities: [['Karachi', 'Asia/Karachi'], ['Lahore', 'Asia/Karachi'], ['Islamabad', 'Asia/Karachi']] },
  { c: 'Bangladesh', cities: [['Dhaka', 'Asia/Dhaka'], ['Chattogram', 'Asia/Dhaka']] },
  { c: 'Sri Lanka', cities: [['Colombo', 'Asia/Colombo']] },
  { c: 'Singapore', cities: [['Singapore', 'Asia/Singapore']] },
  { c: 'Malaysia', cities: [['Kuala Lumpur', 'Asia/Kuala_Lumpur'], ['Penang', 'Asia/Kuala_Lumpur']] },
  { c: 'Indonesia', cities: [['Jakarta', 'Asia/Jakarta'], ['Bandung', 'Asia/Jakarta'], ['Surabaya', 'Asia/Jakarta'], ['Bali (Denpasar)', 'Asia/Makassar']] },
  { c: 'Philippines', cities: [['Manila', 'Asia/Manila'], ['Cebu City', 'Asia/Manila'], ['Davao City', 'Asia/Manila']] },
  { c: 'Vietnam', cities: [['Ho Chi Minh City', 'Asia/Ho_Chi_Minh'], ['Hanoi', 'Asia/Ho_Chi_Minh'], ['Da Nang', 'Asia/Ho_Chi_Minh']] },
  { c: 'Thailand', cities: [['Bangkok', 'Asia/Bangkok'], ['Chiang Mai', 'Asia/Bangkok']] },
  { c: 'Japan', cities: [['Tokyo', 'Asia/Tokyo'], ['Osaka', 'Asia/Tokyo'], ['Kyoto', 'Asia/Tokyo'], ['Fukuoka', 'Asia/Tokyo'], ['Nagoya', 'Asia/Tokyo']] },
  { c: 'South Korea', cities: [['Seoul', 'Asia/Seoul'], ['Busan', 'Asia/Seoul'], ['Incheon', 'Asia/Seoul']] },
  { c: 'China', cities: [['Shanghai', 'Asia/Shanghai'], ['Beijing', 'Asia/Shanghai'], ['Shenzhen', 'Asia/Shanghai'], ['Guangzhou', 'Asia/Shanghai'], ['Hangzhou', 'Asia/Shanghai'], ['Chengdu', 'Asia/Shanghai']] },
  { c: 'Hong Kong', cities: [['Hong Kong', 'Asia/Hong_Kong']] },
  { c: 'Taiwan', cities: [['Taipei', 'Asia/Taipei'], ['Taichung', 'Asia/Taipei']] },
  { c: 'Australia', cities: [['Sydney', 'Australia/Sydney'], ['Melbourne', 'Australia/Melbourne'], ['Brisbane', 'Australia/Brisbane'], ['Perth', 'Australia/Perth'], ['Adelaide', 'Australia/Adelaide'], ['Canberra', 'Australia/Sydney']] },
  { c: 'New Zealand', cities: [['Auckland', 'Pacific/Auckland'], ['Wellington', 'Pacific/Auckland'], ['Christchurch', 'Pacific/Auckland']] },
];
