// Generates the Ed25519 license keypair.
//   license-admin/private-key.js — SIGNS licenses; compiled into the admin
//     generator so it works anywhere it is built. Anyone with repo access
//     can therefore mint licenses; never ship the generator to users.
//   license-public.key           — embedded in the user app; verify-only.
// Re-running rotates the pair: old licenses stop validating in apps built
// with the new public key, so rebuild and redistribute after rotating.
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const PRIV = path.join(__dirname, '..', 'license-admin', 'private-key.js');
const PUB = path.join(__dirname, '..', 'license-public.key');

if (fs.existsSync(PRIV) && !process.argv.includes('--rotate')) {
  console.error('Keypair already exists. Use --rotate to replace it (invalidates all issued licenses).');
  process.exit(1);
}

const { publicKey, privateKey } = crypto.generateKeyPairSync('ed25519');
const pem = privateKey.export({ type: 'pkcs8', format: 'pem' });
fs.writeFileSync(PRIV, `// Generated by scripts/license-keygen.js — license signing key. Do not distribute.\nmodule.exports = ${JSON.stringify(pem)};\n`);
fs.writeFileSync(PUB, publicKey.export({ type: 'spki', format: 'pem' }));
console.log('Wrote', PRIV);
console.log('Wrote', PUB);
